### ISSUE TITLE
Windows ENOENT filesystem failures with batali cache

### ISSUE THREAD

**Issue by webframp** [spox/batali#88]
I was trying to run `batali install` and ran into this:

```
[ERROR]: Reason - No such file or directory @ rb_sysopen - C:/Users/SESCRIVA/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi4xMC43L2Rvd25sb2Fk/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection/resource_list.rb
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Users/SESCRIVA/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi4xMC43L2Rvd25sb2Fk/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection/resource_list.rb
```

tried scrubbing the cache with `batali cache -s` and reinstalling but it fails with the same message on compat_resource. Anything further I can do to debug?

**Comment by chrisroberts** [comment]
Are you still seeing this behavior? What's the version it's attempting to install?

**Comment by webframp** [comment]
I'll try to recreate and update you

**Comment by webframp** [comment]
I tried changing the cache path in the .batali file and I don't get the same error. Although I do get an error maybe it's not directly related:

```
[Batali]: Readying installation destination... complete!
[Batali]: Installing cookbooks... error!
[ERROR]: Reason - unknown file type: C:/src/chef/infra-repo/.batali_cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi45LjEvZG93bmxvYWQ=/compat_resource/./files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb
ERROR: RuntimeError: unknown file type: C:/src/chef/infra-repo/.batali_cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi45LjEvZG93bmxvYWQ=/compat_resource/./files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1387:in `copy'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
C:/Users/sescriva/AppData/Local/chefdk/gem/ruby/2.3.0/gems/batali-0.4.10/lib/batali/command/install.rb:38:in `block (5 levels) in execute!'
```

**Comment by webframp** [comment]
So, in other words yes still happening:
```
[Batali]: Readying installation destination... complete!
[Batali]: Installing cookbooks... error!
[ERROR]: Reason - No such file or directory @ rb_sysopen - C:/Users/sescriva/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi4xNi4xL2Rvd25sb2Fk/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection/resource_list.rb
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Users/sescriva/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi4xNi4xL2Rvd25sb2Fk/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection/resource_list.rb
```

**Comment by webframp** [comment]
Was reported by someone else recently, still a regular issue on Windows. Will try to debug this

**Comment by webframp** [comment]
Tested changes from #92 and here's the output:
```
[DEBUG]: Cache directory to persist cookbooks: C:\Users\sescriva\AppData\Local/.batali/cache
[DEBUG]: Copying assets from `C:/Users/sescriva/AppData/Local/Temp/d20170116-9764-mb6liz` to `cookbooks/octopus-0.2.10`
[DEBUG]: Completed unit install for: octopus<0.2.10>
[DEBUG]: Copying assets from `C:/Users/sescriva/AppData/Local/Temp/d20170116-9764-gj13ql` to `cookbooks/appserver-0.2.1`
[DEBUG]: Completed unit install for: appserver<0.2.1>
error!
[ERROR]: Reason - No such file or directory - Failed to locate asset within `C:\Users\sescriva\AppData\Local/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL3dpbmRvd3MvdmVyc2lvbnMvMi4xLjEvZG93bmxvYWQ=`
ERROR: Errno::ENOENT: No such file or directory - Failed to locate asset within `C:\Users\sescriva\AppData\Local/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL3dpbmRvd3MvdmVyc2lvbnMvMi4xLjEvZG93bmxvYWQ=`
```

Note that the two cookbooks mentioned are internal cookbooks, defined in the Batali file.

**Comment by webframp** [comment]
Tested a few more times, same result although the directory is created:
```
[ERROR]: Reason - No such file or directory - Failed to locate asset within `C:\Users\sescriva\AppData\Local/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL3dpbmRvd3MvdmVyc2lvbnMvMi4xLjEvZG93bmxvYWQ=`
ERROR: Errno::ENOENT: No such file or directory - Failed to locate asset within `C:\Users\sescriva\AppData\Local/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL3dpbmRvd3MvdmVyc2lvbnMvMi4xLjEvZG93bmxvYWQ=`

C:\src\chef\infra-repo [debug +1 ~4 -0 !]> ls C:\Users\sescriva\AppData\Local/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL3dpbmRvd3MvdmVyc2lvbnMvMi4xLjEvZG93bmxvYWQ=

    Directory:  C:\src\chef\infra-repo

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d-----        1/16/2017   5:41 PM        1   windows
-a----        1/16/2017   5:41 PM    52.45KB asset
```

**Comment by webframp** [comment]
I think this might just be hitting the windows filename MAX_PATH character limit, for example if I call `.Length` on the string:

```
$ "C:/Users/sescriva/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi4xNi4zL2Rvd25sb2Fk/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection/resource_list.rb".Length
263
```

**Comment by universam1** [comment]
Same issue here `batali update` errors out which seams to be a path length issue

```
[Batali]: Installing cookbooks... error!
[ERROR]: Reason - No such file or directory @ rb_sysopen - C:/Users/slang2/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi4xNi4zL2Rvd25sb2Fk/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection/resource_list.rb
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Users/slang2/.batali/cache/site/remote_site/aHR0cHM6Ly9zdXBlcm1hcmtldC5jaGVmLmlvOjQ0My9hcGkvdjEvY29va2Jvb2tzL2NvbXBhdF9yZXNvdXJjZS92ZXJzaW9ucy8xMi4xNi4zL2Rvd25sb2Fk/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection/resource_list.rb
```
Any workaround possible?
Thanks!
